name: bender
description: A library for talking to Bender.
version: 1.0.0
homepage: https://www.github.com/Workiva/bender.dart
author: George Lesica <george.lesica@workiva.com>

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  logging: ^0.11.3
  meta: ^1.0.2

dev_dependencies:
  test: ^0.12.0
